[package]
name = "kvs"
version = "0.1.0"
authors = ["SaltyKitkat <sun-yk19@mails.tsinghua.edu.cn>"]
edition = "2018"
description = "this is something wrote just for learning and probably useless"

[[bin]]
name = "kvs"
path = "src/bin/kvs.rs"

[dependencies]
clap = "2.33.3"


[dev-dependencies]
assert_cmd = "1.0.5"
predicates = "1.0.8"
